apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dply
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: lakshminarayanam/gitops-argo-app:31
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
